title: Rafael Granza — Engineering Journal
description: Personal engineering log, challenges, and a manifesto of intention.
remote_theme: cotes2020/jekyll-theme-chirpy
markdown: kramdown
show_excerpts: true
